# Generated by Django 5.2.1 on 2025-07-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
